#import <Foundation/NSString.h>

// MDK: Monet Default Key
#define MDK_OWNER			@"MONET"
#define MDK_NUMBER		22

#define MDK_MASTER_VOLUME		@"MasterVolume"
#define MDK_VOCAL_TRACT_LENGTH	@"VocalTractLength"
#define MDK_TEMPERATURE		@"Temperature"
#define MDK_BALANCE		@"Balance"
#define MDK_BREATHINESS		@"Breathiness"
#define MDK_LOSS_FACTOR		@"LossFactor"

#define MDK_THROAT_CUTTOFF	@"ThroatCuttoff"
#define MDK_THROAT_VOLUME		@"ThroatVolume"
#define MDK_APERTURE_SCALING	@"ApertureScaling"
#define MDK_MOUTH_COEF		@"MouthCoef"
#define MDK_NOSE_COEF		@"NoseCoef"
#define MDK_MIX_OFFSET		@"MixOffset"

#define MDK_N1			@"N1"
#define MDK_N2			@"N2"
#define MDK_N3			@"N3"
#define MDK_N4			@"N4"
#define MDK_N5			@"N5"

#define MDK_TP			@"Tp"
#define MDK_TN_MIN		@"TnMin"
#define MDK_TN_MAX		@"TnMax"

#define MDK_GP_SHAPE		@"GpShape"
#define MDK_NOISE_MODULATION	@"NoiseModulation"

#define MASTER_VOLUME_DEF		@"60"
#define VOCAL_TRACT_LENGTH_DEF		@"17.5"
#define TEMPERATURE_DEF			@"25"
#define BALANCE_DEF			@"0"
#define BREATHINESS_DEF			@"1"
#define LOSS_FACTOR_DEF			@"0.5"
#define THROAT_CUTTOFF_DEF		@"1500"
#define THROAT_VOLUME_DEF		@"6"
#define APERTURE_SCALING_DEF		@"3.05"
#define MOUTH_COEF_DEF			@"5000"
#define NOSE_COEF_DEF			@"5000"
#define MIX_OFFSET_DEF			@"54"
#define N1_DEF				@"1.35"
#define N2_DEF				@"1.96"
#define N3_DEF				@"1.91"
#define N4_DEF				@"1.3"
#define N5_DEF				@"0.73"
#define TP_DEF				@"40"
#define TN_MIN_DEF			@"16"
#define TN_MAX_DEF			@"32"
#define GP_SHAPE_DEF			@"PULSE"
#define NOISE_MODULATION_DEF		@"ON"
