before-all:: 
	$(LN_S) -f ../../Applications/Monet/MMSynthesisParameters.m
	$(LN_S) -f ../../Applications/Monet/MMSynthesisParameters.h
	$(LN_S) -f ../../Applications/Monet/MonetDefaults.h


after-clean:: 
	rm -rf MMSynthesisParameters.m
	rm -rf MMSynthesisParameters.h
	rm -rf MonetDefaults.h
